### ISSUE TITLE
No suitable servers found (but the server is online and reachable)

### ISSUE THREAD

**Issue by MrPowerGamerBR** [mongodb/mongo-php-driver#484]
### Description

I'm trying to connect to my MongoDB server with the PHP driver, however it always throws "Uncaught MongoDB\Driver\Exception\ConnectionTimeoutException: No suitable servers found (`serverSelectionTryOnce` set):"

First, yes, the server is online and reachable, I can connect to the MongoDB server with "mongo" and my Java applications are able to connect without any issues to the server.

I already tried connecting to 127.0.0.1 and localhost, same issue.

I already tried restarting httpd and mongod, same issue.

I already tried binding the MongoDB server to 0.0.0.0 instead of 127.0.0.1, same issue.

Yes, MongoDB drivers are installed, they are active in PHP Info.

Yes, MongoDB is listening on the default MongoDB port.

No, there isn't any errors in MongoDB's log.

Yes, the script and the MongoDB server is in the same machine.

Nothing was changed in MongoDB's server configuration, so it is still using the default values.

I already tried searching about this issue on Google, however everyone says that "your MongoDB server is offline" (mine isn't) or "your MongoDB server is corrupted" (it isn't, because, if it was corrupted, I wouldn't be able to connect via "mongo" and via my Java app (right?))

### Environment

MongoDB PHP version: 1.2.1

MongoDB shell version: 3.2.10 (now updated to 3.4.0)

PHP version: 7.0.13

https://gist.github.com/MrPowerGamerBR/5be376c957f4daa96d247de3e5a3e68f

### Test Script

```
<?php
require_once __DIR__ . "/vendor/autoload.php";

ini_set('display_errors', 1);
ini_set('display_startup_errors', 1);
error_reporting(E_ALL);

// connect to mongodb
$manager = new MongoDB\Driver\Manager("mongodb://localhost:27017");

$command = new MongoDB\Driver\Command(array("ping" => 1));
$result = $manager->executeCommand("test", $command);

var_dump($result, $result->toArray());
?>
```

### Expected and Actual Behavior

That it would work without any errors.

```
Fatal error: Uncaught MongoDB\Driver\Exception\ConnectionTimeoutException: No suitable servers found (`serverSelectionTryOnce` set): [connection refused calling ismaster on 'localhost:27017'] in /var/www/html/mongo.php:12 Stack trace: #0 /var/www/html/mongo.php(12): MongoDB\Driver\Manager->executeCommand('test', Object(MongoDB\Driver\Command)) #1 {main} thrown in /var/www/html/mongo.php on line 12
```

**Comment by jmikola** [comment]
Can you attempt to collect some trace information via the [`mongodb.debug`](http://php.net/manual/en/mongodb.configuration.php#ini.mongodb.debug) INI setting? You can either use "stdout", "stderr" (useful for a CLI environment), or a directory (where new files will be created per request, which is useful for a web SAPI).

**Comment by MrPowerGamerBR** [comment]
@jmikola I hope this is what you need:

```
[Fri Dec 09 17:33:20 2016] [notice] SELinux policy enabled; httpd running as context unconfined_u:system_r:httpd_t:s0
[Fri Dec 09 17:33:20 2016] [notice] suEXEC mechanism enabled (wrapper: /usr/sbin/suexec)
[Fri Dec 09 17:33:20 2016] [notice] Digest: generating secret for digest authentication ...
[Fri Dec 09 17:33:20 2016] [notice] Digest: done
PHP Warning:  Module 'json' already loaded in Unknown on line 0
[2016-12-09T22:33:20+00:00]     mongoc: TRACE   > ENTRY: _mongoc_linux_distro_scanner_get_distro():390
[2016-12-09T22:33:20+00:00]     mongoc: TRACE   > ENTRY: _mongoc_linux_distro_scanner_read_key_value_file():158
[2016-12-09T22:33:20+00:00]     mongoc: TRACE   > TRACE: _mongoc_linux_distro_scanner_read_key_value_file():172 No permission to read from /etc/os-release: errno: 2
[2016-12-09T22:33:20+00:00]     mongoc: TRACE   >  EXIT: _mongoc_linux_distro_scanner_read_key_value_file():173
[2016-12-09T22:33:20+00:00]     mongoc: TRACE   > ENTRY: _mongoc_linux_distro_scanner_read_key_value_file():158
[2016-12-09T22:33:20+00:00]     mongoc: TRACE   > ENTRY: _process_line():95
[2016-12-09T22:33:20+00:00]     mongoc: TRACE   > TRACE: _process_line():124 Found name: CentOS
[2016-12-09T22:33:20+00:00]     mongoc: TRACE   >  EXIT: _process_line():132
[2016-12-09T22:33:20+00:00]     mongoc: TRACE   > ENTRY: _process_line():95
[2016-12-09T22:33:20+00:00]     mongoc: TRACE   > TRACE: _process_line():129 Found version: 6
[2016-12-09T22:33:20+00:00]     mongoc: TRACE   >  EXIT: _process_line():132
[2016-12-09T22:33:20+00:00]     mongoc: TRACE   >  EXIT: _mongoc_linux_distro_scanner_read_key_value_file():204
[2016-12-09T22:33:20+00:00]     mongoc: TRACE   >  EXIT: _mongoc_linux_distro_scanner_get_distro():413
[2016-12-09T22:33:22+00:00]     PHONGO: DEBUG   > Connection string: 'mongodb://localhost:27017'
[2016-12-09T22:33:22+00:00]     PHONGO: DEBUG   > Creating Manager, phongo-1.2.1[stable] - mongoc-1.5.0(bundled), libbson-1.5.0(bundled), php-7.0.13
[2016-12-09T22:33:22+00:00]     mongoc: TRACE   > ENTRY: mongoc_topology_description_init():54
[2016-12-09T22:33:22+00:00]     mongoc: TRACE   >  EXIT: mongoc_topology_description_init():75
[2016-12-09T22:33:22+00:00]     mongoc: TRACE   > ENTRY: mongoc_server_description_init():94
[2016-12-09T22:33:22+00:00]     mongoc: TRACE   >  EXIT: mongoc_server_description_init():131
[2016-12-09T22:33:22+00:00]    cluster: TRACE   > ENTRY: mongoc_cluster_init():1760
[2016-12-09T22:33:22+00:00]    cluster: TRACE   >  EXIT: mongoc_cluster_init():1785
[2016-12-09T22:33:22+00:00]     PHONGO: DEBUG   > Created client hash: a:3:{s:3:"uri";s:25:"mongodb://localhost:27017";s:7:"options";N;s:13:"driverOptions";N;}

[2016-12-09T22:33:22+00:00]     cursor: TRACE   > ENTRY: _mongoc_cursor_new_with_opts():255
[2016-12-09T22:33:22+00:00]     cursor: TRACE   >  EXIT: _mongoc_cursor_new_with_opts():353
[2016-12-09T22:33:22+00:00]     cursor: TRACE   > ENTRY: mongoc_cursor_next():1699
[2016-12-09T22:33:22+00:00]     cursor: TRACE   > TRACE: mongoc_cursor_next():1704 cursor_id(0)
[2016-12-09T22:33:22+00:00]     cursor: TRACE   > ENTRY: _mongoc_cursor_next():1770
[2016-12-09T22:33:22+00:00]     cursor: TRACE   > ENTRY: _mongoc_cursor_initial_query():615
[2016-12-09T22:33:22+00:00]     cursor: TRACE   > ENTRY: _mongoc_cursor_fetch_stream():574
[2016-12-09T22:33:22+00:00]    cluster: TRACE   > ENTRY: _mongoc_cluster_stream_for_optype():1850
[2016-12-09T22:33:22+00:00] topology_scanner: TRACE   > ENTRY: mongoc_topology_scanner_node_connect_tcp():427
[2016-12-09T22:33:22+00:00]     socket: TRACE   > ENTRY: mongoc_socket_new():727
[2016-12-09T22:33:22+00:00]     socket: TRACE   > ENTRY: _mongoc_socket_setnodelay():271
[2016-12-09T22:33:22+00:00]     socket: TRACE   >  EXIT: _mongoc_socket_setnodelay():283
[2016-12-09T22:33:22+00:00]     socket: TRACE   >  EXIT: mongoc_socket_new():751
[2016-12-09T22:33:22+00:00]     socket: TRACE   > ENTRY: mongoc_socket_connect():590
[2016-12-09T22:33:22+00:00]     socket: TRACE   > TRACE: _mongoc_socket_capture_errno():336 setting errno: 13
[2016-12-09T22:33:22+00:00]     socket: TRACE   > TRACE: _mongoc_socket_errno_is_again():360 errno is: 13
[2016-12-09T22:33:22+00:00]     socket: TRACE   >  EXIT: mongoc_socket_connect():622
[2016-12-09T22:33:22+00:00]     stream: TRACE   > ENTRY: _mongoc_stream_socket_poll():226
[2016-12-09T22:33:22+00:00]     socket: TRACE   > ENTRY: mongoc_socket_poll():217
[2016-12-09T22:33:22+00:00]     stream: TRACE   >  EXIT: _mongoc_stream_socket_poll():252
[2016-12-09T22:33:22+00:00]     stream: TRACE   > ENTRY: mongoc_stream_failed():79
[2016-12-09T22:33:22+00:00]     stream: TRACE   > ENTRY: _mongoc_stream_socket_failed():89
[2016-12-09T22:33:22+00:00]     stream: TRACE   > ENTRY: _mongoc_stream_socket_destroy():71
[2016-12-09T22:33:22+00:00]     socket: TRACE   > ENTRY: mongoc_socket_close():531
[2016-12-09T22:33:22+00:00]     socket: TRACE   >  EXIT: mongoc_socket_close():556
[2016-12-09T22:33:22+00:00]     stream: TRACE   >  EXIT: _mongoc_stream_socket_destroy():82
[2016-12-09T22:33:22+00:00]     stream: TRACE   >  EXIT: _mongoc_stream_socket_failed():93
[2016-12-09T22:33:22+00:00]     stream: TRACE   >  EXIT: mongoc_stream_failed():89
[2016-12-09T22:33:22+00:00]     mongoc: TRACE   > ENTRY: mongoc_server_description_handle_ismaster():497
[2016-12-09T22:33:22+00:00]     mongoc: TRACE   >  EXIT: mongoc_server_description_handle_ismaster():504
[2016-12-09T22:33:22+00:00]     mongoc: TRACE   > TRACE: mongoc_topology_description_handle_ismaster():1729 No transition entry to Single for Unknown
[2016-12-09T22:33:22+00:00]     mongoc: TRACE   > ENTRY: mongoc_topology_description_select():747
[2016-12-09T22:33:22+00:00]     mongoc: TRACE   > TRACE: mongoc_topology_description_select():761 Topology type single, [localhost:27017] is down
[2016-12-09T22:33:22+00:00]     mongoc: TRACE   >  EXIT: mongoc_topology_description_select():762
[2016-12-09T22:33:22+00:00]    cluster: TRACE   >  EXIT: _mongoc_cluster_stream_for_optype():1860
[2016-12-09T22:33:22+00:00]     cursor: TRACE   >  EXIT: _mongoc_cursor_fetch_stream():591
[2016-12-09T22:33:22+00:00]     cursor: TRACE   >  GOTO: _mongoc_cursor_initial_query():622 done
[2016-12-09T22:33:22+00:00]     cursor: TRACE   >  EXIT: _mongoc_cursor_initial_query():651
[2016-12-09T22:33:22+00:00]     cursor: TRACE   >  EXIT: _mongoc_cursor_next():1819
[2016-12-09T22:33:22+00:00]     cursor: TRACE   >  EXIT: mongoc_cursor_next():1743
[2016-12-09T22:33:22+00:00]     cursor: TRACE   > ENTRY: mongoc_cursor_error():1658
[2016-12-09T22:33:22+00:00]     cursor: TRACE   > ENTRY: _mongoc_cursor_error():1676
[2016-12-09T22:33:22+00:00]     cursor: TRACE   >  EXIT: _mongoc_cursor_error():1686
[2016-12-09T22:33:22+00:00]     cursor: TRACE   >  EXIT: mongoc_cursor_error():1668
[2016-12-09T22:33:22+00:00]     cursor: TRACE   > ENTRY: mongoc_cursor_destroy():509
[2016-12-09T22:33:22+00:00]     cursor: TRACE   > ENTRY: _mongoc_cursor_destroy():526
[2016-12-09T22:33:22+00:00]     cursor: TRACE   >  EXIT: _mongoc_cursor_destroy():565
[2016-12-09T22:33:22+00:00]     cursor: TRACE   >  EXIT: mongoc_cursor_destroy():519
[Fri Dec 09 17:33:22 2016] [error] [client 189.69.17.250] PHP Fatal error:  Uncaught MongoDB\\Driver\\Exception\\ConnectionTimeoutException: No suitable servers found (`serverSelectionTryOnce` set): [connection refused calling ismaster on 'localhost:27017'] in /var/www/html/mongo.php:12\nStack trace:\n#0 /var/www/html/mongo.php(12): MongoDB\\Driver\\Manager->executeCommand('test', Object(MongoDB\\Driver\\Command))\n#1 {main}\n  thrown in /var/www/html/mongo.php on line 12
[2016-12-09T22:33:22+00:00]     mongoc: DEBUG   > Not destroying persistent client for Manager
```

**Comment by jmikola** [comment]
These two lines stand out:

```
[2016-12-09T22:33:22+00:00]     socket: TRACE   > TRACE: _mongoc_socket_capture_errno():336 setting errno: 13
[2016-12-09T22:33:22+00:00]     socket: TRACE   > TRACE: _mongoc_socket_errno_is_again():360 errno is: 13
```

Error code 13 is EACCES ("Permission Denied") (see: [here](http://www.virtsync.com/c-error-codes-include-errno)), which suggests an operating system issue. The PHP driver and libmongoc appear to be functioning properly in this situation, as libmongoc simply isn't able to open a socket to the server.

Your log also references SELinux, which leads me to believe your issue is related to these two Stack Overflow threads:

 * http://stackoverflow.com/a/28748703/162228
 * http://stackoverflow.com/a/15117996/162228

Before adjusting the configuration, you can also run the same script through the CLI environment to confirm that it's specific to SELinux's restrictions for web servers.

**Comment by MrPowerGamerBR** [comment]
@jmikola 

Here is the log after running the script with "php mongo.php"

It seems it did work, right?
```
[root@ns520510 html]# php mongo.php
PHP Warning:  Module 'json' already loaded in Unknown on line 0
[2016-12-09T23:46:20+00:00]     mongoc: TRACE   > ENTRY: _mongoc_linux_distro_scanner_get_distro():390
[2016-12-09T23:46:20+00:00]     mongoc: TRACE   > ENTRY: _mongoc_linux_distro_scanner_read_key_value_file():158
[2016-12-09T23:46:20+00:00]     mongoc: TRACE   > TRACE: _mongoc_linux_distro_scanner_read_key_value_file():172 No permission to read from /etc/os-release: errno: 2
[2016-12-09T23:46:20+00:00]     mongoc: TRACE   >  EXIT: _mongoc_linux_distro_scanner_read_key_value_file():173
[2016-12-09T23:46:20+00:00]     mongoc: TRACE   > ENTRY: _mongoc_linux_distro_scanner_read_key_value_file():158
[2016-12-09T23:46:20+00:00]     mongoc: TRACE   > ENTRY: _process_line():95
[2016-12-09T23:46:20+00:00]     mongoc: TRACE   > TRACE: _process_line():124 Found name: CentOS
[2016-12-09T23:46:20+00:00]     mongoc: TRACE   >  EXIT: _process_line():132
[2016-12-09T23:46:20+00:00]     mongoc: TRACE   > ENTRY: _process_line():95
[2016-12-09T23:46:20+00:00]     mongoc: TRACE   > TRACE: _process_line():129 Found version: 6
[2016-12-09T23:46:20+00:00]     mongoc: TRACE   >  EXIT: _process_line():132
[2016-12-09T23:46:20+00:00]     mongoc: TRACE   >  EXIT: _mongoc_linux_distro_scanner_read_key_value_file():204
[2016-12-09T23:46:20+00:00]     mongoc: TRACE   >  EXIT: _mongoc_linux_distro_scanner_get_distro():413
[2016-12-09T23:46:20+00:00]     PHONGO: DEBUG   > Connection string: 'mongodb://localhost:27017'
[2016-12-09T23:46:20+00:00]     PHONGO: DEBUG   > Creating Manager, phongo-1.2.1[stable] - mongoc-1.5.0(bundled), libbson-1.5.0(bundled), php-7.0.13
[2016-12-09T23:46:20+00:00]     mongoc: TRACE   > ENTRY: mongoc_topology_description_init():54
[2016-12-09T23:46:20+00:00]     mongoc: TRACE   >  EXIT: mongoc_topology_description_init():75
[2016-12-09T23:46:20+00:00]     mongoc: TRACE   > ENTRY: mongoc_server_description_init():94
[2016-12-09T23:46:20+00:00]     mongoc: TRACE   >  EXIT: mongoc_server_description_init():131
[2016-12-09T23:46:20+00:00]    cluster: TRACE   > ENTRY: mongoc_cluster_init():1760
[2016-12-09T23:46:20+00:00]    cluster: TRACE   >  EXIT: mongoc_cluster_init():1785
[2016-12-09T23:46:20+00:00]     PHONGO: DEBUG   > Created client hash: a:3:{s:3:"uri";s:25:"mongodb://localhost:27017";s:7:"options";N;s:13:"driverOptions";N;}

[2016-12-09T23:46:20+00:00]     cursor: TRACE   > ENTRY: _mongoc_cursor_new_with_opts():255
[2016-12-09T23:46:20+00:00]     cursor: TRACE   >  EXIT: _mongoc_cursor_new_with_opts():353
[2016-12-09T23:46:20+00:00]     cursor: TRACE   > ENTRY: mongoc_cursor_next():1699
[2016-12-09T23:46:20+00:00]     cursor: TRACE   > TRACE: mongoc_cursor_next():1704 cursor_id(0)
[2016-12-09T23:46:20+00:00]     cursor: TRACE   > ENTRY: _mongoc_cursor_next():1770
[2016-12-09T23:46:20+00:00]     cursor: TRACE   > ENTRY: _mongoc_cursor_initial_query():615
[2016-12-09T23:46:20+00:00]     cursor: TRACE   > ENTRY: _mongoc_cursor_fetch_stream():574
[2016-12-09T23:46:20+00:00]    cluster: TRACE   > ENTRY: _mongoc_cluster_stream_for_optype():1850
[2016-12-09T23:46:20+00:00] topology_scanner: TRACE   > ENTRY: mongoc_topology_scanner_node_connect_tcp():427
[2016-12-09T23:46:20+00:00]     socket: TRACE   > ENTRY: mongoc_socket_new():727
[2016-12-09T23:46:20+00:00]     socket: TRACE   > ENTRY: _mongoc_socket_setnodelay():271
[2016-12-09T23:46:20+00:00]     socket: TRACE   >  EXIT: _mongoc_socket_setnodelay():283
[2016-12-09T23:46:20+00:00]     socket: TRACE   >  EXIT: mongoc_socket_new():751
[2016-12-09T23:46:20+00:00]     socket: TRACE   > ENTRY: mongoc_socket_connect():590
[2016-12-09T23:46:20+00:00]     socket: TRACE   > TRACE: _mongoc_socket_capture_errno():336 setting errno: 115
[2016-12-09T23:46:20+00:00]     socket: TRACE   > TRACE: _mongoc_socket_errno_is_again():360 errno is: 115
[2016-12-09T23:46:20+00:00]     socket: TRACE   > ENTRY: _mongoc_socket_wait():113
[2016-12-09T23:46:20+00:00]     socket: TRACE   >  EXIT: _mongoc_socket_wait():154
[2016-12-09T23:46:20+00:00]     socket: TRACE   >  EXIT: mongoc_socket_connect():615
[2016-12-09T23:46:20+00:00]     stream: TRACE   > ENTRY: _mongoc_stream_socket_poll():226
[2016-12-09T23:46:20+00:00]     socket: TRACE   > ENTRY: mongoc_socket_poll():217
[2016-12-09T23:46:20+00:00]     stream: TRACE   >  EXIT: _mongoc_stream_socket_poll():252
[2016-12-09T23:46:20+00:00]     stream: TRACE   > ENTRY: mongoc_stream_writev():149
[2016-12-09T23:46:20+00:00]     stream: TRACE   > TRACE: mongoc_stream_writev():161 writev = 0x1065980 [9]
[2016-12-09T23:46:20+00:00]     stream: TRACE   > 00000:  4e 01 00 00 01 00 00 00  00 00 00 00 d4 07 00 00  N . . . . . . .  . . . . . . . .
[2016-12-09T23:46:20+00:00]     stream: TRACE   > 00010:  04 00 00 00 61 64 6d 69  6e 2e 24 63 6d 64 00 00  . . . . a d m i  n . $ c m d . .
[2016-12-09T23:46:20+00:00]     stream: TRACE   > 00020:  00 00 00 ff ff ff ff 27  01 00 00 10 69 73 4d 61  . . . . . . . '  . . . . i s M a
[2016-12-09T23:46:20+00:00]     stream: TRACE   > 00030:  73 74 65 72 00 01 00 00  00 03 63 6c 69 65 6e 74  s t e r . . . .  . . c l i e n t
[2016-12-09T23:46:20+00:00]     stream: TRACE   > 00040:  00 0c 01 00 00 03 64 72  69 76 65 72 00 43 00 00  . . . . . . d r  i v e r . C . .
[2016-12-09T23:46:20+00:00]     stream: TRACE   > 00050:  00 02 6e 61 6d 65 00 19  00 00 00 6d 6f 6e 67 6f  . . n a m e . .  . . . m o n g o
[2016-12-09T23:46:20+00:00]     stream: TRACE   > 00060:  63 20 2f 20 65 78 74 2d  6d 6f 6e 67 6f 64 62 3a  c   /   e x t -  m o n g o d b :
[2016-12-09T23:46:20+00:00]     stream: TRACE   > 00070:  50 48 50 00 02 76 65 72  73 69 6f 6e 00 0e 00 00  P H P . . v e r  s i o n . . . .
[2016-12-09T23:46:20+00:00]     stream: TRACE   > 00080:  00 31 2e 35 2e 30 20 2f  20 31 2e 32 2e 31 00 00  . 1 . 5 . 0   /    1 . 2 . 1 . .
[2016-12-09T23:46:20+00:00]     stream: TRACE   > 00090:  03 6f 73 00 4e 00 00 00  02 74 79 70 65 00 06 00  . o s . N . . .  . t y p e . . .
[2016-12-09T23:46:20+00:00]     stream: TRACE   > 000a0:  00 00 4c 69 6e 75 78 00  02 6e 61 6d 65 00 07 00  . . L i n u x .  . n a m e . . .
[2016-12-09T23:46:20+00:00]     stream: TRACE   > 000b0:  00 00 43 65 6e 74 4f 53  00 02 76 65 72 73 69 6f  . . C e n t O S  . . v e r s i o
[2016-12-09T23:46:20+00:00]     stream: TRACE   > 000c0:  6e 00 02 00 00 00 36 00  02 61 72 63 68 69 74 65  n . . . . . 6 .  . a r c h i t e
[2016-12-09T23:46:20+00:00]     stream: TRACE   > 000d0:  63 74 75 72 65 00 07 00  00 00 78 38 36 5f 36 34  c t u r e . . .  . . x 8 6 _ 6 4
[2016-12-09T23:46:20+00:00]     stream: TRACE   > 000e0:  00 00 02 70 6c 61 74 66  6f 72 6d 00 5c 00 00 00  . . . p l a t f  o r m . \ . . .
[2016-12-09T23:46:20+00:00]     stream: TRACE   > 000f0:  63 66 67 3d 30 78 33 30  63 39 20 70 6f 73 69 78  c f g = 0 x 3 0  c 9   p o s i x
[2016-12-09T23:46:20+00:00]     stream: TRACE   > 00100:  3d 32 30 30 38 30 39 20  43 43 3d 47 43 43 20 34  = 2 0 0 8 0 9    C C = G C C   4
[2016-12-09T23:46:20+00:00]     stream: TRACE   > 00110:  2e 34 2e 37 20 32 30 31  32 30 33 31 33 20 28 52  . 4 . 7   2 0 1  2 0 3 1 3   ( R
[2016-12-09T23:46:20+00:00]     stream: TRACE   > 00120:  65 64 20 48 61 74 20 34  2e 34 2e 37 2d 31 37 29  e d   H a t   4  . 4 . 7 - 1 7 )
[2016-12-09T23:46:20+00:00]     stream: TRACE   > 00130:  20 43 46 4c 41 47 53 3d  2d 67 20 2d 4f 32 20 2f    C F L A G S =  - g   - O 2   /
[2016-12-09T23:46:20+00:00]     stream: TRACE   > 00140:  20 50 48 50 20 37 2e 30  2e 31 33 00 00 00          P H P   7 . 0  . 1 3 . . .
[2016-12-09T23:46:20+00:00]     stream: TRACE   > ENTRY: _mongoc_stream_socket_writev():202
[2016-12-09T23:46:20+00:00]     socket: TRACE   > ENTRY: mongoc_socket_sendv():1089
[2016-12-09T23:46:20+00:00]     socket: TRACE   > ENTRY: _mongoc_socket_try_sendv():998
[2016-12-09T23:46:20+00:00]     socket: TRACE   > TRACE: _mongoc_socket_try_sendv():1004 sendbuf = 0x106a520 [9]
[2016-12-09T23:46:20+00:00]     socket: TRACE   > 00000:  4e 01 00 00 01 00 00 00  00 00 00 00 d4 07 00 00  N . . . . . . .  . . . . . . . .
[2016-12-09T23:46:20+00:00]     socket: TRACE   > 00010:  04 00 00 00 61 64 6d 69  6e 2e 24 63 6d 64 00 00  . . . . a d m i  n . $ c m d . .
[2016-12-09T23:46:20+00:00]     socket: TRACE   > 00020:  00 00 00 ff ff ff ff 27  01 00 00 10 69 73 4d 61  . . . . . . . '  . . . . i s M a
[2016-12-09T23:46:20+00:00]     socket: TRACE   > 00030:  73 74 65 72 00 01 00 00  00 03 63 6c 69 65 6e 74  s t e r . . . .  . . c l i e n t
[2016-12-09T23:46:20+00:00]     socket: TRACE   > 00040:  00 0c 01 00 00 03 64 72  69 76 65 72 00 43 00 00  . . . . . . d r  i v e r . C . .
[2016-12-09T23:46:20+00:00]     socket: TRACE   > 00050:  00 02 6e 61 6d 65 00 19  00 00 00 6d 6f 6e 67 6f  . . n a m e . .  . . . m o n g o
[2016-12-09T23:46:20+00:00]     socket: TRACE   > 00060:  63 20 2f 20 65 78 74 2d  6d 6f 6e 67 6f 64 62 3a  c   /   e x t -  m o n g o d b :
[2016-12-09T23:46:20+00:00]     socket: TRACE   > 00070:  50 48 50 00 02 76 65 72  73 69 6f 6e 00 0e 00 00  P H P . . v e r  s i o n . . . .
[2016-12-09T23:46:20+00:00]     socket: TRACE   > 00080:  00 31 2e 35 2e 30 20 2f  20 31 2e 32 2e 31 00 00  . 1 . 5 . 0   /    1 . 2 . 1 . .
[2016-12-09T23:46:20+00:00]     socket: TRACE   > 00090:  03 6f 73 00 4e 00 00 00  02 74 79 70 65 00 06 00  . o s . N . . .  . t y p e . . .
[2016-12-09T23:46:20+00:00]     socket: TRACE   > 000a0:  00 00 4c 69 6e 75 78 00  02 6e 61 6d 65 00 07 00  . . L i n u x .  . n a m e . . .
[2016-12-09T23:46:20+00:00]     socket: TRACE   > 000b0:  00 00 43 65 6e 74 4f 53  00 02 76 65 72 73 69 6f  . . C e n t O S  . . v e r s i o
[2016-12-09T23:46:20+00:00]     socket: TRACE   > 000c0:  6e 00 02 00 00 00 36 00  02 61 72 63 68 69 74 65  n . . . . . 6 .  . a r c h i t e
[2016-12-09T23:46:20+00:00]     socket: TRACE   > 000d0:  63 74 75 72 65 00 07 00  00 00 78 38 36 5f 36 34  c t u r e . . .  . . x 8 6 _ 6 4
[2016-12-09T23:46:20+00:00]     socket: TRACE   > 000e0:  00 00 02 70 6c 61 74 66  6f 72 6d 00 5c 00 00 00  . . . p l a t f  o r m . \ . . .
[2016-12-09T23:46:20+00:00]     socket: TRACE   > 000f0:  63 66 67 3d 30 78 33 30  63 39 20 70 6f 73 69 78  c f g = 0 x 3 0  c 9   p o s i x
[2016-12-09T23:46:20+00:00]     socket: TRACE   > 00100:  3d 32 30 30 38 30 39 20  43 43 3d 47 43 43 20 34  = 2 0 0 8 0 9    C C = G C C   4
[2016-12-09T23:46:20+00:00]     socket: TRACE   > 00110:  2e 34 2e 37 20 32 30 31  32 30 33 31 33 20 28 52  . 4 . 7   2 0 1  2 0 3 1 3   ( R
[2016-12-09T23:46:20+00:00]     socket: TRACE   > 00120:  65 64 20 48 61 74 20 34  2e 34 2e 37 2d 31 37 29  e d   H a t   4  . 4 . 7 - 1 7 )
[2016-12-09T23:46:20+00:00]     socket: TRACE   > 00130:  20 43 46 4c 41 47 53 3d  2d 67 20 2d 4f 32 20 2f    C F L A G S =  - g   - O 2   /
[2016-12-09T23:46:20+00:00]     socket: TRACE   > 00140:  20 50 48 50 20 37 2e 30  2e 31 33 00 00 00          P H P   7 . 0  . 1 3 . . .
[2016-12-09T23:46:20+00:00]     socket: TRACE   > TRACE: _mongoc_socket_try_sendv():1020 Send 334 out of 4 bytes
[2016-12-09T23:46:20+00:00]     socket: TRACE   >  EXIT: _mongoc_socket_try_sendv():1050
[2016-12-09T23:46:20+00:00]     socket: TRACE   > TRACE: mongoc_socket_sendv():1100 Sent 334 (of 4) out of iovcnt=9
[2016-12-09T23:46:20+00:00]     socket: TRACE   > TRACE: mongoc_socket_sendv():1125 still got bytes left: sent -= iov_len: 334 -= 4
[2016-12-09T23:46:20+00:00]     socket: TRACE   > TRACE: mongoc_socket_sendv():1125 still got bytes left: sent -= iov_len: 330 -= 4
[2016-12-09T23:46:20+00:00]     socket: TRACE   > TRACE: mongoc_socket_sendv():1125 still got bytes left: sent -= iov_len: 326 -= 4
[2016-12-09T23:46:20+00:00]     socket: TRACE   > TRACE: mongoc_socket_sendv():1125 still got bytes left: sent -= iov_len: 322 -= 4
[2016-12-09T23:46:20+00:00]     socket: TRACE   > TRACE: mongoc_socket_sendv():1125 still got bytes left: sent -= iov_len: 318 -= 4
[2016-12-09T23:46:20+00:00]     socket: TRACE   > TRACE: mongoc_socket_sendv():1125 still got bytes left: sent -= iov_len: 314 -= 11
[2016-12-09T23:46:20+00:00]     socket: TRACE   > TRACE: mongoc_socket_sendv():1125 still got bytes left: sent -= iov_len: 303 -= 4
[2016-12-09T23:46:20+00:00]     socket: TRACE   > TRACE: mongoc_socket_sendv():1125 still got bytes left: sent -= iov_len: 299 -= 4
[2016-12-09T23:46:20+00:00]     socket: TRACE   > TRACE: mongoc_socket_sendv():1125 still got bytes left: sent -= iov_len: 295 -= 295
[2016-12-09T23:46:20+00:00]     socket: TRACE   > TRACE: mongoc_socket_sendv():1134 Finished the iovecs
[2016-12-09T23:46:20+00:00]     socket: TRACE   >  EXIT: mongoc_socket_sendv():1165
[2016-12-09T23:46:20+00:00]     socket: TRACE   > TRACE: mongoc_socket_errno():307 Current errno: 115
[2016-12-09T23:46:20+00:00]     stream: TRACE   >  EXIT: _mongoc_stream_socket_writev():208
[2016-12-09T23:46:20+00:00]     stream: TRACE   >  EXIT: mongoc_stream_writev():164
[2016-12-09T23:46:20+00:00]     stream: TRACE   > ENTRY: _mongoc_stream_socket_poll():226
[2016-12-09T23:46:20+00:00]     socket: TRACE   > ENTRY: mongoc_socket_poll():217
[2016-12-09T23:46:20+00:00]     stream: TRACE   >  EXIT: _mongoc_stream_socket_poll():252
[2016-12-09T23:46:20+00:00]     buffer: TRACE   > ENTRY: _mongoc_buffer_try_append_from_stream():292
[2016-12-09T23:46:20+00:00]     stream: TRACE   > ENTRY: mongoc_stream_read():268
[2016-12-09T23:46:20+00:00]     stream: TRACE   > ENTRY: mongoc_stream_readv():226
[2016-12-09T23:46:20+00:00]     stream: TRACE   > ENTRY: _mongoc_stream_socket_readv():139
[2016-12-09T23:46:20+00:00]     socket: TRACE   > ENTRY: mongoc_socket_recv():797
[2016-12-09T23:46:20+00:00]     socket: TRACE   >  EXIT: mongoc_socket_recv():826
[2016-12-09T23:46:20+00:00]     stream: TRACE   >  EXIT: _mongoc_stream_socket_readv():188
[2016-12-09T23:46:20+00:00]     stream: TRACE   > TRACE: mongoc_stream_readv():236 readv = 0x7ffe3550b070 [1]
[2016-12-09T23:46:20+00:00]     stream: TRACE   > 00000:  cd 00 00 00                                       . . . .
[2016-12-09T23:46:20+00:00]     stream: TRACE   >  EXIT: mongoc_stream_readv():239
[2016-12-09T23:46:20+00:00]     stream: TRACE   >  EXIT: mongoc_stream_read():280
[2016-12-09T23:46:20+00:00]     buffer: TRACE   >  EXIT: _mongoc_buffer_try_append_from_stream():322
[2016-12-09T23:46:20+00:00]     buffer: TRACE   > ENTRY: _mongoc_buffer_try_append_from_stream():292
[2016-12-09T23:46:20+00:00]     stream: TRACE   > ENTRY: mongoc_stream_read():268
[2016-12-09T23:46:20+00:00]     stream: TRACE   > ENTRY: mongoc_stream_readv():226
[2016-12-09T23:46:20+00:00]     stream: TRACE   > ENTRY: _mongoc_stream_socket_readv():139
[2016-12-09T23:46:20+00:00]     socket: TRACE   > ENTRY: mongoc_socket_recv():797
[2016-12-09T23:46:20+00:00]     socket: TRACE   >  EXIT: mongoc_socket_recv():826
[2016-12-09T23:46:20+00:00]     stream: TRACE   >  EXIT: _mongoc_stream_socket_readv():188
[2016-12-09T23:46:20+00:00]     stream: TRACE   > TRACE: mongoc_stream_readv():236 readv = 0x7ffe3550b070 [1]
[2016-12-09T23:46:20+00:00]     stream: TRACE   > 00000:  9a d1 07 00 01 00 00 00  01 00 00 00 08 00 00 00  . . . . . . . .  . . . . . . . .
[2016-12-09T23:46:20+00:00]     stream: TRACE   > 00010:  00 00 00 00 00 00 00 00  00 00 00 00 01 00 00 00  . . . . . . . .  . . . . . . . .
[2016-12-09T23:46:20+00:00]     stream: TRACE   > 00020:  a9 00 00 00 08 69 73 6d  61 73 74 65 72 00 01 10  . . . . . i s m  a s t e r . . .
[2016-12-09T23:46:20+00:00]     stream: TRACE   > 00030:  6d 61 78 42 73 6f 6e 4f  62 6a 65 63 74 53 69 7a  m a x B s o n O  b j e c t S i z
[2016-12-09T23:46:20+00:00]     stream: TRACE   > 00040:  65 00 00 00 00 01 10 6d  61 78 4d 65 73 73 61 67  e . . . . . . m  a x M e s s a g
[2016-12-09T23:46:20+00:00]     stream: TRACE   > 00050:  65 53 69 7a 65 42 79 74  65 73 00 00 6c dc 02 10  e S i z e B y t  e s . . l . . .
[2016-12-09T23:46:20+00:00]     stream: TRACE   > 00060:  6d 61 78 57 72 69 74 65  42 61 74 63 68 53 69 7a  m a x W r i t e  B a t c h S i z
[2016-12-09T23:46:20+00:00]     stream: TRACE   > 00070:  65 00 e8 03 00 00 09 6c  6f 63 61 6c 54 69 6d 65  e . . . . . . l  o c a l T i m e
[2016-12-09T23:46:20+00:00]     stream: TRACE   > 00080:  00 12 fc fa e5 58 01 00  00 10 6d 61 78 57 69 72  . . . . . X . .  . . m a x W i r
[2016-12-09T23:46:20+00:00]     stream: TRACE   > 00090:  65 56 65 72 73 69 6f 6e  00 05 00 00 00 10 6d 69  e V e r s i o n  . . . . . . m i
[2016-12-09T23:46:20+00:00]     stream: TRACE   > 000a0:  6e 57 69 72 65 56 65 72  73 69 6f 6e 00 00 00 00  n W i r e V e r  s i o n . . . .
[2016-12-09T23:46:20+00:00]     stream: TRACE   > 000b0:  00 08 72 65 61 64 4f 6e  6c 79 00 00 01 6f 6b 00  . . r e a d O n  l y . . . o k .
[2016-12-09T23:46:20+00:00]     stream: TRACE   > 000c0:  00 00 00 00 00 00 f0 3f  00                       . . . . . . . ?  .
[2016-12-09T23:46:20+00:00]     stream: TRACE   >  EXIT: mongoc_stream_readv():239
[2016-12-09T23:46:20+00:00]     stream: TRACE   >  EXIT: mongoc_stream_read():280
[2016-12-09T23:46:20+00:00]     buffer: TRACE   >  EXIT: _mongoc_buffer_try_append_from_stream():322
[2016-12-09T23:46:20+00:00]     mongoc: TRACE   > ENTRY: mongoc_server_description_handle_ismaster():497
[2016-12-09T23:46:20+00:00]     mongoc: TRACE   >  EXIT: mongoc_server_description_handle_ismaster():624
[2016-12-09T23:46:20+00:00]     mongoc: TRACE   > TRACE: mongoc_topology_description_handle_ismaster():1729 No transition entry to Single for Standalone
[2016-12-09T23:46:20+00:00]     mongoc: TRACE   > ENTRY: mongoc_topology_description_select():747
[2016-12-09T23:46:20+00:00]     mongoc: TRACE   >  EXIT: mongoc_topology_description_select():759
[2016-12-09T23:46:20+00:00]    cluster: TRACE   > ENTRY: _mongoc_cluster_stream_for_server():1497
[2016-12-09T23:46:20+00:00]     mongoc: TRACE   > ENTRY: mongoc_server_description_handle_ismaster():497
[2016-12-09T23:46:20+00:00]     mongoc: TRACE   >  EXIT: mongoc_server_description_handle_ismaster():624
[2016-12-09T23:46:20+00:00]    cluster: TRACE   >  EXIT: _mongoc_cluster_stream_for_server():1529
[2016-12-09T23:46:20+00:00]    cluster: TRACE   >  EXIT: _mongoc_cluster_stream_for_optype():1869
[2016-12-09T23:46:20+00:00]     cursor: TRACE   >  EXIT: _mongoc_cursor_fetch_stream():591
[2016-12-09T23:46:20+00:00]     cursor: TRACE   > ENTRY: _mongoc_cursor_op_query():1104
[2016-12-09T23:46:20+00:00]     mongoc: TRACE   > ENTRY: apply_read_preferences():292
[2016-12-09T23:46:20+00:00]     mongoc: TRACE   >  EXIT: apply_read_preferences():345
[2016-12-09T23:46:20+00:00]     cursor: TRACE   > ENTRY: _mongoc_cursor_monitor_legacy_query():665
[2016-12-09T23:46:20+00:00]     cursor: TRACE   >  EXIT: _mongoc_cursor_monitor_legacy_query():670
[2016-12-09T23:46:20+00:00]    cluster: TRACE   > ENTRY: mongoc_cluster_sendv_to_server():2268
[2016-12-09T23:46:20+00:00]     stream: TRACE   > ENTRY: _mongoc_stream_writev_full():490
[2016-12-09T23:46:20+00:00]     stream: TRACE   > ENTRY: mongoc_stream_writev():149
[2016-12-09T23:46:20+00:00]     stream: TRACE   > TRACE: mongoc_stream_writev():161 writev = 0x1069330 [9]
[2016-12-09T23:46:20+00:00]     stream: TRACE   > 00000:  35 00 00 00 01 00 00 00  00 00 00 00 d4 07 00 00  5 . . . . . . .  . . . . . . . .
[2016-12-09T23:46:20+00:00]     stream: TRACE   > 00010:  04 00 00 00 74 65 73 74  2e 24 63 6d 64 00 00 00  . . . . t e s t  . $ c m d . . .
[2016-12-09T23:46:20+00:00]     stream: TRACE   > 00020:  00 00 01 00 00 00 0f 00  00 00 10 70 69 6e 67 00  . . . . . . . .  . . . p i n g .
[2016-12-09T23:46:20+00:00]     stream: TRACE   > 00030:  01 00 00 00 00                                    . . . . .
[2016-12-09T23:46:21+00:00]     stream: TRACE   > ENTRY: _mongoc_stream_socket_writev():202
[2016-12-09T23:46:21+00:00]     socket: TRACE   > ENTRY: mongoc_socket_sendv():1089
[2016-12-09T23:46:21+00:00]     socket: TRACE   > ENTRY: _mongoc_socket_try_sendv():998
[2016-12-09T23:46:21+00:00]     socket: TRACE   > TRACE: _mongoc_socket_try_sendv():1004 sendbuf = 0x1069550 [9]
[2016-12-09T23:46:21+00:00]     socket: TRACE   > 00000:  35 00 00 00 01 00 00 00  00 00 00 00 d4 07 00 00  5 . . . . . . .  . . . . . . . .
[2016-12-09T23:46:21+00:00]     socket: TRACE   > 00010:  04 00 00 00 74 65 73 74  2e 24 63 6d 64 00 00 00  . . . . t e s t  . $ c m d . . .
[2016-12-09T23:46:21+00:00]     socket: TRACE   > 00020:  00 00 01 00 00 00 0f 00  00 00 10 70 69 6e 67 00  . . . . . . . .  . . . p i n g .
[2016-12-09T23:46:21+00:00]     socket: TRACE   > 00030:  01 00 00 00 00                                    . . . . .
[2016-12-09T23:46:21+00:00]     socket: TRACE   > TRACE: _mongoc_socket_try_sendv():1020 Send 53 out of 4 bytes
[2016-12-09T23:46:21+00:00]     socket: TRACE   >  EXIT: _mongoc_socket_try_sendv():1050
[2016-12-09T23:46:21+00:00]     socket: TRACE   > TRACE: mongoc_socket_sendv():1100 Sent 53 (of 4) out of iovcnt=9
[2016-12-09T23:46:21+00:00]     socket: TRACE   > TRACE: mongoc_socket_sendv():1125 still got bytes left: sent -= iov_len: 53 -= 4
[2016-12-09T23:46:21+00:00]     socket: TRACE   > TRACE: mongoc_socket_sendv():1125 still got bytes left: sent -= iov_len: 49 -= 4
[2016-12-09T23:46:21+00:00]     socket: TRACE   > TRACE: mongoc_socket_sendv():1125 still got bytes left: sent -= iov_len: 45 -= 4
[2016-12-09T23:46:21+00:00]     socket: TRACE   > TRACE: mongoc_socket_sendv():1125 still got bytes left: sent -= iov_len: 41 -= 4
[2016-12-09T23:46:21+00:00]     socket: TRACE   > TRACE: mongoc_socket_sendv():1125 still got bytes left: sent -= iov_len: 37 -= 4
[2016-12-09T23:46:21+00:00]     socket: TRACE   > TRACE: mongoc_socket_sendv():1125 still got bytes left: sent -= iov_len: 33 -= 10
[2016-12-09T23:46:21+00:00]     socket: TRACE   > TRACE: mongoc_socket_sendv():1125 still got bytes left: sent -= iov_len: 23 -= 4
[2016-12-09T23:46:21+00:00]     socket: TRACE   > TRACE: mongoc_socket_sendv():1125 still got bytes left: sent -= iov_len: 19 -= 4
[2016-12-09T23:46:21+00:00]     socket: TRACE   > TRACE: mongoc_socket_sendv():1125 still got bytes left: sent -= iov_len: 15 -= 15
[2016-12-09T23:46:21+00:00]     socket: TRACE   > TRACE: mongoc_socket_sendv():1134 Finished the iovecs
[2016-12-09T23:46:21+00:00]     socket: TRACE   >  EXIT: mongoc_socket_sendv():1165
[2016-12-09T23:46:21+00:00]     socket: TRACE   > TRACE: mongoc_socket_errno():307 Current errno: 0
[2016-12-09T23:46:21+00:00]     stream: TRACE   >  EXIT: _mongoc_stream_socket_writev():208
[2016-12-09T23:46:21+00:00]     stream: TRACE   >  EXIT: mongoc_stream_writev():164
[2016-12-09T23:46:21+00:00]     stream: TRACE   > TRACE: _mongoc_stream_writev_full():497 writev returned: 53
[2016-12-09T23:46:21+00:00]     stream: TRACE   >  EXIT: _mongoc_stream_writev_full():521
[2016-12-09T23:46:21+00:00]    cluster: TRACE   >  EXIT: mongoc_cluster_sendv_to_server():2378
[2016-12-09T23:46:21+00:00]    cluster: TRACE   > ENTRY: mongoc_cluster_try_recv():2417
[2016-12-09T23:46:21+00:00]    cluster: TRACE   > TRACE: mongoc_cluster_try_recv():2426 Waiting for reply from server_id "1"
[2016-12-09T23:46:21+00:00]     buffer: TRACE   > ENTRY: _mongoc_buffer_append_from_stream():150
[2016-12-09T23:46:21+00:00]     stream: TRACE   > ENTRY: mongoc_stream_read():268
[2016-12-09T23:46:21+00:00]     stream: TRACE   > ENTRY: mongoc_stream_readv():226
[2016-12-09T23:46:21+00:00]     stream: TRACE   > ENTRY: _mongoc_stream_socket_readv():139
[2016-12-09T23:46:21+00:00]     socket: TRACE   > ENTRY: mongoc_socket_recv():797
[2016-12-09T23:46:21+00:00]     socket: TRACE   >  EXIT: mongoc_socket_recv():826
[2016-12-09T23:46:21+00:00]     stream: TRACE   >  EXIT: _mongoc_stream_socket_readv():188
[2016-12-09T23:46:21+00:00]     stream: TRACE   > TRACE: mongoc_stream_readv():236 readv = 0x7ffe3550b0b0 [1]
[2016-12-09T23:46:21+00:00]     stream: TRACE   > 00000:  35 00 00 00                                       5 . . .
[2016-12-09T23:46:21+00:00]     stream: TRACE   >  EXIT: mongoc_stream_readv():239
[2016-12-09T23:46:21+00:00]     stream: TRACE   >  EXIT: mongoc_stream_read():280
[2016-12-09T23:46:21+00:00]     buffer: TRACE   >  EXIT: _mongoc_buffer_append_from_stream():186
[2016-12-09T23:46:21+00:00]     buffer: TRACE   > ENTRY: _mongoc_buffer_append_from_stream():150
[2016-12-09T23:46:21+00:00]     stream: TRACE   > ENTRY: mongoc_stream_read():268
[2016-12-09T23:46:21+00:00]     stream: TRACE   > ENTRY: mongoc_stream_readv():226
[2016-12-09T23:46:21+00:00]     stream: TRACE   > ENTRY: _mongoc_stream_socket_readv():139
[2016-12-09T23:46:21+00:00]     socket: TRACE   > ENTRY: mongoc_socket_recv():797
[2016-12-09T23:46:21+00:00]     socket: TRACE   >  EXIT: mongoc_socket_recv():826
[2016-12-09T23:46:21+00:00]     stream: TRACE   >  EXIT: _mongoc_stream_socket_readv():188
[2016-12-09T23:46:21+00:00]     stream: TRACE   > TRACE: mongoc_stream_readv():236 readv = 0x7ffe3550b0b0 [1]
[2016-12-09T23:46:21+00:00]     stream: TRACE   > 00000:  9b d1 07 00 01 00 00 00  01 00 00 00 08 00 00 00  . . . . . . . .  . . . . . . . .
[2016-12-09T23:46:21+00:00]     stream: TRACE   > 00010:  00 00 00 00 00 00 00 00  00 00 00 00 01 00 00 00  . . . . . . . .  . . . . . . . .
[2016-12-09T23:46:21+00:00]     stream: TRACE   > 00020:  11 00 00 00 01 6f 6b 00  00 00 00 00 00 00 f0 3f  . . . . . o k .  . . . . . . . ?
[2016-12-09T23:46:21+00:00]     stream: TRACE   > 00030:  00                                                .
[2016-12-09T23:46:21+00:00]     stream: TRACE   >  EXIT: mongoc_stream_readv():239
[2016-12-09T23:46:21+00:00]     stream: TRACE   >  EXIT: mongoc_stream_read():280
[2016-12-09T23:46:21+00:00]     buffer: TRACE   >  EXIT: _mongoc_buffer_append_from_stream():186
[2016-12-09T23:46:21+00:00]    cluster: TRACE   >  EXIT: mongoc_cluster_try_recv():2484
[2016-12-09T23:46:21+00:00]     mongoc: TRACE   > ENTRY: _mongoc_rpc_parse_error():842
[2016-12-09T23:46:21+00:00]     mongoc: TRACE   > ENTRY: _mongoc_populate_cmd_error():767
[2016-12-09T23:46:21+00:00]     mongoc: TRACE   >  EXIT: _mongoc_populate_cmd_error():773
[2016-12-09T23:46:21+00:00]     mongoc: TRACE   >  EXIT: _mongoc_rpc_parse_error():858
[2016-12-09T23:46:21+00:00]     cursor: TRACE   > ENTRY: _mongoc_cursor_monitor_succeeded():736
[2016-12-09T23:46:21+00:00]     cursor: TRACE   >  EXIT: _mongoc_cursor_monitor_succeeded():741
[2016-12-09T23:46:21+00:00]     mongoc: TRACE   > ENTRY: apply_read_prefs_result_cleanup():352
[2016-12-09T23:46:21+00:00]     mongoc: TRACE   >  EXIT: apply_read_prefs_result_cleanup():360
[2016-12-09T23:46:21+00:00]     cursor: TRACE   >  EXIT: _mongoc_cursor_op_query():1245
[2016-12-09T23:46:21+00:00]     mongoc: TRACE   > ENTRY: mongoc_server_description_destroy():153
[2016-12-09T23:46:21+00:00]     mongoc: TRACE   >  EXIT: mongoc_server_description_destroy():159
[2016-12-09T23:46:21+00:00]     cursor: TRACE   >  EXIT: _mongoc_cursor_initial_query():651
[2016-12-09T23:46:21+00:00]     cursor: TRACE   >  EXIT: _mongoc_cursor_next():1819
[2016-12-09T23:46:21+00:00]     cursor: TRACE   >  EXIT: mongoc_cursor_next():1743
[2016-12-09T23:46:21+00:00]     cursor: TRACE   > ENTRY: mongoc_cursor_next():1699
[2016-12-09T23:46:21+00:00]     cursor: TRACE   > TRACE: mongoc_cursor_next():1704 cursor_id(0)
[2016-12-09T23:46:21+00:00]     cursor: TRACE   > ENTRY: _mongoc_cursor_next():1770
[2016-12-09T23:46:21+00:00]     cursor: TRACE   >  EXIT: _mongoc_cursor_next():1819
[2016-12-09T23:46:21+00:00]     cursor: TRACE   >  EXIT: mongoc_cursor_next():1743
[2016-12-09T23:46:21+00:00]     cursor: TRACE   > ENTRY: mongoc_cursor_error():1658
[2016-12-09T23:46:21+00:00]     cursor: TRACE   > ENTRY: _mongoc_cursor_error():1676
[2016-12-09T23:46:21+00:00]     cursor: TRACE   >  EXIT: _mongoc_cursor_error():1689
[2016-12-09T23:46:21+00:00]     cursor: TRACE   >  EXIT: mongoc_cursor_error():1668
object(MongoDB\Driver\Cursor)#4 (9) {
  ["database"]=>
  string(4) "test"
  ["collection"]=>
  NULL
  ["query"]=>
  NULL
  ["command"]=>
  object(MongoDB\Driver\Command)#2 (1) {
    ["command"]=>
    object(stdClass)#7 (1) {
      ["ping"]=>
      int(1)
    }
  }
  ["readPreference"]=>
  NULL
  ["isDead"]=>
  bool(true)
  ["currentIndex"]=>
  int(1)
  ["currentDocument"]=>
  NULL
  ["server"]=>
  [2016-12-09T23:46:21+00:00]     mongoc: TRACE   > ENTRY: mongoc_server_description_handle_ismaster():497
[2016-12-09T23:46:21+00:00]     mongoc: TRACE   >  EXIT: mongoc_server_description_handle_ismaster():624
[2016-12-09T23:46:21+00:00]     mongoc: TRACE   > ENTRY: mongoc_server_description_destroy():153
[2016-12-09T23:46:21+00:00]     mongoc: TRACE   >  EXIT: mongoc_server_description_destroy():159
object(MongoDB\Driver\Server)#5 (10) {
    ["host"]=>
    string(9) "localhost"
    ["port"]=>
    int(27017)
    ["type"]=>
    int(1)
    ["is_primary"]=>
    bool(false)
    ["is_secondary"]=>
    bool(false)
    ["is_arbiter"]=>
    bool(false)
    ["is_hidden"]=>
    bool(false)
    ["is_passive"]=>
    bool(false)
    ["last_is_master"]=>
    array(9) {
      ["ismaster"]=>
      bool(true)
      ["maxBsonObjectSize"]=>
      int(16777216)
      ["maxMessageSizeBytes"]=>
      int(48000000)
      ["maxWriteBatchSize"]=>
      int(1000)
      ["localTime"]=>
      object(MongoDB\BSON\UTCDateTime)#7 (1) {
        ["milliseconds"]=>
        string(13) "1481327180818"
      }
      ["maxWireVersion"]=>
      int(5)
      ["minWireVersion"]=>
      int(0)
      ["readOnly"]=>
      bool(false)
      ["ok"]=>
      float(1)
    }
    ["round_trip_time"]=>
    int(0)
  }
}
array(1) {
  [0]=>
  object(stdClass)#6 (1) {
    ["ok"]=>
    float(1)
  }
}
[2016-12-09T23:46:21+00:00]     cursor: TRACE   > ENTRY: mongoc_cursor_destroy():509
[2016-12-09T23:46:21+00:00]     cursor: TRACE   > ENTRY: _mongoc_cursor_destroy():526
[2016-12-09T23:46:21+00:00]     cursor: TRACE   >  EXIT: _mongoc_cursor_destroy():565
[2016-12-09T23:46:21+00:00]     cursor: TRACE   >  EXIT: mongoc_cursor_destroy():519
[2016-12-09T23:46:21+00:00]     mongoc: DEBUG   > Not destroying persistent client for Manager
```

**Comment by MrPowerGamerBR** [comment]
@jmikola 😄 

![https://a.pomf.cat/bbgoex.png](https://a.pomf.cat/bbgoex.png)

using

```
setsebool -P httpd_can_network_connect on
```

fixed the issue.

**Comment by JefferyHus** [comment]
for anyone trying to use @MrPowerGamerBR solution, you will have to know that your kernel must be built using SELinux and not Aparmor, for me I had the same issue all i did is checked my server to find that mongo was not running ```mongo``` did the work.

**Comment by SergioMLeon** [comment]
Hi @JefferyHus what you mean by "mongo was not running mongo"? I'm having the same issue even changed php and driver version and still having the same issue, makes me think that is problem of the db server

**Comment by Messhias** [comment]
I tried all the solution in the thread and nothing works, it's already a quite headache to me that, this driver is working or not?

**Comment by Messhias** [comment]
> @jmikola 😄
> 
> ![https://a.pomf.cat/bbgoex.png](https://camo.githubusercontent.com/508680817a8a0d87d10891123c524022c6c06e6e/68747470733a2f2f612e706f6d662e6361742f6262676f65782e706e67)
> 
> using
> 
> ```
> setsebool -P httpd_can_network_connect on
> ```
> fixed the issue.
> 
> EDIT: 2018 update, it seems the old image expired and was replaced with something else... oh well, the image was just an screenshot showing that it was working correctly.

This is not work for MacOS system, so this is isn't a real solution since we have to consider this is a driver and should be work for all the OS's.

**Comment by jmikola** [comment]
@Messhias: The `setsebool` command that resolved this issue was a specific solution for SELinux, so it would not apply to macOS. The conclusion in https://github.com/mongodb/mongo-php-driver/issues/484#issuecomment-266118217 was also that there was no driver issue at play here, as the operating system's own configuration was impeding its ability to open a socket.

Rather than continue discussion on this closed thread, I'd suggest that you open a new issue and provide as much information requested in the issue template as possible. At the very least, you should describe the deployment of your application and database server(s). In the OP's case, they were connecting to a local database server but that may not necessarily be the case in your deployment. Additionally, it will be helpful to see the complete exception message and trace logs (mentioned in https://github.com/mongodb/mongo-php-driver/issues/484#issuecomment-266097039) to diagnose the specific error code for the failed connection.

**Comment by Messhias** [comment]
@jmikola thanks for your answer, I solved the issue in the smartest way possible, removed the MongoDB of application and now I'm using Redis, but thank you anyway.

**Comment by JefferyHus** [comment]
> Hi @JefferyHus what you mean by "mongo was not running mongo"? I'm having the same issue even changed php and driver version and still having the same issue, makes me think that is problem of the db server

I missed a comma there, I mean that by running `mongo` command line the issue was fixed. But make sure that you do respect what I wrote there about the kernel

**Comment by amjithps** [comment]
MongoDB\Driver\Exception\ConnectionTimeoutException
No servers yet eligible for rescan 

vendor/mongodb/mongodb/src/functions.php:487


I am still facing the same issue. PHP8.1 Anyone knows how to fix this. its a headace!

**Comment by nazirahmad7340** [comment]
MongoDB server with the PHP driver, however, it always throws "Uncaught MongoDB\Driver\Exception\ConnectionTimeoutException: No suitable servers found (serverSelectionTryOnce set):"

I had the same problem with the MongoDB atlas but after a lot of searching finally I found that MongoDB port 27017 is closed in Firewall. 

Open the port in your server firewall.  will work.

**Comment by sajubusinesscompassllc** [comment]
> MongoDB\Driver\Exception\ConnectionTimeoutException No servers yet eligible for rescan
> 
> vendor/mongodb/mongodb/src/functions.php:487
> 
> I am still facing the same issue. PHP8.1 Anyone knows how to fix this. its a headace!

Am also facing same issue

But it works with NodeJs & getting issue only PHP

**Comment by sajumani** [comment]
> MongoDB\Driver\Exception\ConnectionTimeoutException No servers yet eligible for rescan
> 
> vendor/mongodb/mongodb/src/functions.php:487
> 
> I am still facing the same issue. PHP8.1 Anyone knows how to fix this. its a headace!

Am also facing same issue

But It works with NodeJs & only issue with PHP

**Comment by jmikola** [comment]
I'm going to lock this thread as the OP's original issue was resolved long ago.

The FAQ section in the PHPLIB documentation now has a section on [Server Selection Failures](https://www.mongodb.com/docs/php-library/current/faq/#server-selection-failures), which should provide some guidance on how to distinguish different types of "No suitable servers found" errors. 

Server selection errors _generally_ have to do with circumstances outside of the PHP driver itself (e.g. the app or database server's network configuration, SSL certificates), but understanding how to interpret the exception message should assist folks in determining that. In the event the PHP driver does seem a likely culprit, reporting a new issue is preferable to following up on old threads that are likely to have a different root cause.
